### PR TITLE
Revert "Revert "Revert "Add JSON and new search functions"""

### PR DESCRIPTION
**Pull request by homemadestea58**
Links-Portal links loading not working
Possibly JSON Issue Parsing

### CODE REVIEW

**Comment by michaeldaltonau** [comment]
@Homemadestea58 
> Links-Portal links loading not working
> Possibly JSON Issue Parsing

### Could you **_please_** open an issue stating:
- The device, browser and versions
- Screenshots of what is happening
- Are you running off github pages, links-p.cf, or a local copy on Apache

For now I'll revert this PR until there is an issue stating how to reproduce this bug

**Comment by SuperMario22922** [comment]
I managed to test all of the json parsing and it worked but only on links-p.cf

**Comment by michaeldaltonau** [comment]
> I managed to test all of the json parsing and it worked but only on links-p.cf

@HSAK5G 

What doesn't it work on? (GitHub pages, local copy with Apache?)

**Comment by SuperMario22922** [comment]
GitHub pages. Did not test local copy with Apache

**Comment by michaeldaltonau** [comment]
> GitHub pages. Did not test local copy with Apache

## Your GitHub pages or Homemadestea58's?

Also, could you check with @Homemadestea58 to see what they are doing to get this error, and what domain (GitHub pages, or localhost[apache])

**Comment by SuperMario22922** [comment]
When merged we tried to access on both of our devices. Both did not work!

**Comment by michaeldaltonau** [comment]
## Please answer the following questions
1. Was this on the filtered network (you know what I mean) or the other network?
2. What browser did you use to do this (Please mention browser, device, device version, and browser version)
3. If on iOS/iPadOS was a VPN used
4. Did you access it via GitHub pages? If true, who's fork did you use?
5. Did you access it via links-p.cf?
6. Did you access it via a local copy (Apache)?
7. Was JavaScript enabled on the browser?

### Then comment back with the results

### After that, reproduce the results on a desktop browser with a dev console, and make another comment with the results of the JS console.

**Pull request merged**
